{
  "task": "classification",
  "gpu_ids": [
    0
  ],
  "n_channels": 3,
  "datasets": {
    "train": {
      "name": "train_dataset",
      "dataroot": "sample/sample_data",
      "dataloader_shuffle": true,
      "dataloader_num_workers": 2,
      "dataloader_batch_size": 2,
      "phase": "train",
      "n_channels": 3
    },
    "test": {
      "name": "test_dataset",
      "dataroot": "sample/sample_data",
      "phase": "test",
      "n_channels": 3
    }
  },
  "path": {
    "root": "crop_classification",
    "pretrained_net": null,
    "task": "crop_classification\\classification",
    "log": "crop_classification\\classification",
    "options": "crop_classification\\classification\\options",
    "models": "crop_classification\\classification\\models",
    "images": "crop_classification\\classification\\images",
    "strict_net": true,
    "pretrained_optimizer": null
  },
  "net": {
    "net_type": "resnet_lstm",
    "max_len": 144,
    "embedding_dim": 512,
    "num_features": 9,
    "class_n": 32,
    "dropout_rate": 0.1
  },
  "train": {
    "lossfn_type": "CrossEntropy",
    "lossfn_weight": 1,
    "scheduler_type": "MultiStepLR",
    "scheduler_milestones": [
      1000000
    ],
    "scheduler_gamma": 0.5,
    "optimizer_type": "adam",
    "optimizer_lr": 0.0001,
    "checkpoint_test": 10,
    "checkpoint_save": 10,
    "checkpoint_print": 1,
    "optimizer_reuse": false
  },
  "opt_path": "options/train_resnet_lstm.yaml",
  "is_train": true,
  "num_gpu": 1,
  "amp": false,
  "resume": true
}